HOST: http://amundsen.com/

--- Sample To-Do Hypermedia API ---
---
Welcome to the our API. Comments support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax
---

-- To Do List --
GET /todo/?filter=fish
> Accept: text/html
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 200
< Content-Type: text/html
<dl class="collection">
  <dt><a href="." class="add">add new item</a></dt>
  <dt><a href="33" class="item">33</a></dt>
  <dd>
    <span class="title">this is a fish</span>
  </dd>
  <dt><a href="44" class="item">44</a></dt>
  <dd>
    <span class="title">this is a fish, too</span>
  </dd>
</dl>


GET /todo/
> Accept: text/html
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 200
< Content-Type: text/html
<dl class="collection">
  <dt><a href="." class="add">add new item</a></dt>
  <dt><form action="."><label for="filter">filter:<input name="filter"></label><input type="submit" /></form></dt>
  <dt><a href="1" class="item">1</a></dt>
  <dd>
    <span class="title">this is title 1</span>
  </dd>
  <dt><a href="2" class="item">2</a></dt>
  <dd>
    <span class="title">this is title 2</span>
  </dd>
</dl>


GET /todo/1
> Accept: text/html
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 200
< Content-Type: text/html
<dl class="collection">
  <dt><a href="/todo/" class="home">home</a></dt>
  <dt><a href="1" class="item">1</a></dt>
  <dd>
    <span class="title">this is title 1</span>
  </dd>
</dl>


POST /todo/
> Accept: text/thml
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
> Content-Type: application/x-www-form-urlencoded
title=this+is+a+new+title
< 201
< Location: /todo/99
< Content-Type: text/html


PUT /todo/1
> Accept: text/html
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
> Content-Type: application/x-www-form-urlencoded
title=this+is+a+new+title+1
< 200
< Content-Type: text/html
<dl class="collection">
  <dt><a href="1" class="item">1</a></dt>
  <dd>
    <span class="title">this is a new title 1</span>
  </dd>
</dl>

DELETE /todo/1
> Accept: text/html
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 204
< Content-Type: text/html

