HOST: http://amundsen.com/

--- To-Do API ---
---
Welcome to the our API. Comments support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax
---

-- Get a list of todo items --
GET /todo/
> Accept: application/json
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 200
< Content-Type: application/json
[
  {id:0,text:'this is some item'};
  {id:1,text:'this is another item'};
  {id:2,text:'this is one more item'};
  {id:3,text:'this is possibly an item'};
]


-- Filter the list of todo items --
GET /todo/?text=one
> Accept: application/json
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 200
< Content-Type: application/json
[
  {id:2,text:'this is one more item'};
]


-- Add a new todo item --
POST /todo/
> Accept: application/json
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 2
< Content-Type: application/x-www-form-urlencoded
text=this+is+a+new+title
< 201
< Location: /todo/99


-- update and existing todo item
PUT /todo/{id}
> Accept: application/json
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 2
< Content-Type: application/x-www-form-urlencoded
text=this+is+a+new+title
< 200
{}

-- Mark a todo item complete --
POST /todo/complete
> Accept: application/json
> Authorization: Basic xxxxxxxxxxxxxxxxxxxx
< 2
< Content-Type: application/x-www-form-urlencode